//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolioProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Skill
    {
        public int SkillID { get; set; }
        [Required(ErrorMessage ="Yetenek baþlýðý gereklidir.")]
        [MinLength(1,ErrorMessage ="Yetenek baþlýðý en az 1 karakter olmalýdýr.")]
        public string SkillName { get; set; }
        [Required(ErrorMessage = "Yetenek deðeri gereklidir.")]
        [Range(1, 100, ErrorMessage = "Yetenek deðeri 1 ile 100 arasýnda olmalýdýr.")]
        public Nullable<byte> Rate { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
